package com.moviepicker.backend.config;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class DatabaseConstraintUpdater implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        try {
            // Automatically drop stale enum check constraints generated by earlier Hibernate runs
            jdbcTemplate.execute("ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_status_check");
            jdbcTemplate.execute("ALTER TABLE votes DROP CONSTRAINT IF EXISTS votes_vote_type_check");
            log.info("Successfully verified and updated database table check constraints.");
        } catch (Exception e) {
            log.debug("Database constraint update skipped: {}", e.getMessage());
        }
    }
}
