-- V1: Initial Database Schema for Movie Picker

-- 1. Sessions Table
CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code VARCHAR(10) NOT NULL UNIQUE,
    host_name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    max_users INT NOT NULL,
    max_suggestions_per_user INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

-- 2. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    display_name VARCHAR(100) NOT NULL,
    joined_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_session_id ON users(session_id);

-- 3. Movie Suggestions Table
CREATE TABLE IF NOT EXISTS movie_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    tmdb_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    poster_path VARCHAR(500),
    overview TEXT,
    release_year INT,
    suggested_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_session_tmdb UNIQUE (session_id, tmdb_id)
);

CREATE INDEX IF NOT EXISTS idx_movie_suggestions_session_id ON movie_suggestions(session_id);
CREATE INDEX IF NOT EXISTS idx_movie_suggestions_session_user ON movie_suggestions(session_id, user_id);

-- 4. Votes Table
CREATE TABLE IF NOT EXISTS votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    movie_suggestion_id BIGINT NOT NULL REFERENCES movie_suggestions(id) ON DELETE CASCADE,
    vote_type VARCHAR(20) NOT NULL,
    voted_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_movie_vote UNIQUE (user_id, movie_suggestion_id)
);

CREATE INDEX IF NOT EXISTS idx_votes_session_id ON votes(session_id);
CREATE INDEX IF NOT EXISTS idx_votes_session_movie ON votes(session_id, movie_suggestion_id);
CREATE INDEX IF NOT EXISTS idx_votes_session_user ON votes(session_id, user_id);
